version: "3"
services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: postgres:latest
    hostname: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: database
