# Use a imagem oficial do Node.js
FROM node:18

# Configurar o diretório de trabalho
WORKDIR /app

# Copiar arquivos do servidor para o contêiner
COPY ./server .

# Instalar dependências
RUN npm install

# Executar os testes
RUN npm test

# Expor a porta do servidor
EXPOSE 8080

# Comando para iniciar o servidor
CMD ["npm", "start"]